version: '2'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  baggins:
    image: 'baggins'
    build:
      context: ./baggins
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "6070:8000"
    volumes:
      - '../app/:/app'
    depends_on:
      - db
 
volumes:
  pgdata:

