# Generated by Django 2.0.1 on 2018-01-08 16:03

from django.db import migrations, models
import django_brfied.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('data_empenho', models.DateField(verbose_name='Data do empenho')),
                ('vinculo', django_brfied.models.ForeignKey(on_delete=None, to='contrato.Vinculo', verbose_name='Vínculo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
