# Generated by Django 2.0.1 on 2018-01-17 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_auto_20180117_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='identificacao',
            field=models.CharField(help_text='Formato: 0001/2018 UORG-UORG-UORG - Evite colocar a descrição aqui', max_length=250, validators=[django.core.validators.RegexValidator(regex='^\\d*/\\d{4} .+')], verbose_name='Identificação'),
        ),
    ]
