# Generated by Django 2.0.1 on 2018-01-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0002_auto_20180117_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcao',
            name='tipo_carga_horaria',
        ),
        migrations.AddField(
            model_name='funcao',
            name='jornada',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Mensal', 'Mensal')], default='Semanal', max_length=10, verbose_name='Jornada'),
        ),
    ]
