# Generated by Django 2.0.1 on 2018-01-18 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0003_auto_20180118_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargaHoraria',
        ),
    ]
