# Generated by Django 2.0.1 on 2018-01-11 17:21

import django.core.validators
from django.db import migrations, models
import django_brfied.models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Telefone', 'Telefone'), ('Celular', 'Celular'), ('VoIP', 'VoIP'), ('E-Mail', 'E-Mail'), ('Instant Message', 'Instant Message'), ('Site', 'Site'), ('Endereço', 'Endereço')], max_length=20, verbose_name='Tipo')),
                ('principal', models.BooleanField(verbose_name='Principal')),
                ('nome', models.CharField(blank=True, max_length=250, null=True, verbose_name='Nome')),
                ('valor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contato')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('prestador', django_brfied.models.ForeignKey(on_delete=None, to='contrato.Prestador', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=250, verbose_name='Identificação do documento')),
                ('arquivo', models.FileField(max_length=250, upload_to='', verbose_name='Comprovante')),
                ('data_envio', models.DateField(auto_now=True, verbose_name='Envio')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tipo', django_brfied.models.ForeignKey(on_delete=None, to='tipo.DocumentacaoCurricular', verbose_name='Tipo')),
                ('vinculo', django_brfied.models.ForeignKey(on_delete=None, to='contrato.Vinculo', verbose_name='Vinculo')),
            ],
            options={
                'verbose_name': 'Documentação curricular',
                'verbose_name_plural': 'Documentações curriculares',
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=250, verbose_name='Identificação do documento')),
                ('arquivo', models.FileField(max_length=250, upload_to='', verbose_name='Comprovante')),
                ('data_envio', models.DateField(auto_now=True, verbose_name='Envio')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('prestador', django_brfied.models.ForeignKey(on_delete=None, to='contrato.Prestador', verbose_name='Prestador')),
                ('tipo', django_brfied.models.ForeignKey(on_delete=None, to='tipo.DocumentacaoPessoal', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Documentação pessoal',
                'verbose_name_plural': 'Documentações pessoais',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(verbose_name='Ordem')),
                ('convocado_em', models.DateField(blank=True, null=True, verbose_name='Convocado em')),
                ('assumiu_em', models.DateField(blank=True, null=True, verbose_name='Assumiu em')),
                ('desistencia_em', models.DateField(blank=True, null=True, verbose_name='Desistência em')),
                ('termo_desistencia', models.CharField(blank=True, max_length=250, null=True, verbose_name='Termo desistência')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('prestador', django_brfied.models.ForeignKey(on_delete=None, to='contrato.Prestador', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AlterField(
            model_name='vaga',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40)], verbose_name='Carga horária'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vaga',
            field=django_brfied.models.ForeignKey(on_delete=None, to='contrato.Vaga', verbose_name='Vaga'),
        ),
    ]
