# Generated by Django 2.0.1 on 2018-01-17 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_auto_20180117_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='carga_horaria',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(168)], verbose_name='Carga horária'),
        ),
    ]
