# Generated by Django 2.1.4 on 2019-02-27 23:35

from django.db import migrations, models
import django_brfied.models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_auto_20180117_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacaocurricular',
            name='arquivo',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='documentacaocurricular',
            name='data_envio',
            field=models.DateField(auto_now=True, null=True, verbose_name='Envio'),
        ),
        migrations.AlterField(
            model_name='documentacaocurricular',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Identificação do documento'),
        ),
        migrations.AlterField(
            model_name='documentacaopessoal',
            name='arquivo',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Comprovante'),
        ),
        migrations.AlterField(
            model_name='documentacaopessoal',
            name='data_envio',
            field=models.DateField(auto_now=True, null=True, verbose_name='Envio'),
        ),
        migrations.AlterField(
            model_name='documentacaopessoal',
            name='valor',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Identificação do documento'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nome_apresentacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nome_civil',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome civil'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da mãe'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='sexo',
            field=django_brfied.models.SexoField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Não declarado')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='data_fim_previsto',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fim previsto'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='data_inicio_previsto',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início previsto'),
        ),
        migrations.AlterField(
            model_name='vinculo',
            name='valor_carga_horaria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor por hora'),
        ),
    ]
