# Generated by Django 2.1.4 on 2019-02-28 11:51

from django.db import migrations, models
import django_brfied.models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0008_auto_20190227_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='endereco_cep',
            field=django_brfied.models.CEPField(blank=True, mask='99999-999', mask_stored=True, max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='endereco_municipio',
            field=django_brfied.models.MunicipioField(blank=True, null=True, on_delete=None, to='django_brfied.Municipio', verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='endereco_referencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='endereco_zona',
            field=models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], max_length=150, null=True, verbose_name='Zona residencial'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='nome_civil',
            field=models.CharField(default='Não informado', max_length=255, verbose_name='Nome civil'),
            preserve_default=False,
        ),
    ]
