# Generated by Django 2.1.7 on 2019-03-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0009_auto_20190228_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(choices=[('Telefone', 'Telefone'), ('Celular', 'Celular'), ('VoIP', 'VoIP'), ('E-Mail', 'E-Mail'), ('Instant Message', 'Instant Message'), ('Site', 'Site'), ('Endereço', 'Endereço')], default='E-Mail', max_length=20, verbose_name='Tipo'),
        ),
    ]
