# Generated by Django 2.0.1 on 2018-01-08 16:03

from django.db import migrations, models
import django_brfied.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Carga horária',
                'verbose_name_plural': 'Cargas horárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoCurricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Documentação curricular',
                'verbose_name_plural': 'Documentações curriculares',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentacaoPessoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Documentação pessoal',
                'verbose_name_plural': 'Documentações pessoais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('tipo_carga_horaria', django_brfied.models.ForeignKey(on_delete=None, to='tipo.CargaHoraria', verbose_name='Carga horária')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['nome'],
            },
        ),
    ]
