# Generated by Django 2.0.1 on 2018-01-17 19:36

from django.db import migrations
import django_brfied.models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcao',
            name='tipo_carga_horaria',
            field=django_brfied.models.ForeignKey(on_delete=None, to='tipo.CargaHoraria', verbose_name='Tipo de carga horária'),
        ),
    ]
